name = "filmospere"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "filmospere.com"
custom_domain = true

[[routes]]
pattern = "www.filmospere.com"
custom_domain = true
